TRUNCATE TABLE interactions RESTART IDENTITY;
TRUNCATE TABLE media RESTART IDENTITY;
TRUNCATE TABLE comments RESTART IDENTITY;
TRUNCATE TABLE friend_requests RESTART IDENTITY;
TRUNCATE TABLE posts RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;

DROP TABLE interactions;
DROP TABLE media;
DROP TABLE comments;
DROP TABLE friend_requests;
DROP TABLE posts;
DROP TABLE users;

